spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml
  datasource:
    url: jdbc:postgresql://postgres-chart-service:5432/payments
    username: program
    password: test